/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
"use strict";

systemDictionary = {
	"gebaeudesteuerung-vis adapter settings": {
		en: "Adapter settings for gebaeudesteuerung-vis",
		de: "Adaptereinstellungen für gebaeudesteuerung-vis",
		ru: "Настройки адаптера для gebaeudesteuerung-vis",
		pt: "Configurações do adaptador para gebaeudesteuerung-vis",
		nl: "Adapterinstellingen voor gebaeudesteuerung-vis",
		fr: "Paramètres d'adaptateur pour gebaeudesteuerung-vis",
		it: "Impostazioni dell'adattatore per gebaeudesteuerung-vis",
		es: "Ajustes del adaptador para gebaeudesteuerung-vis",
		pl: "Ustawienia adaptera dla gebaeudesteuerung-vis",
		uk: "Налаштування адаптера для gebaeudesteuerung-vis",
		"zh-cn": "gebaeudesteuerung-vis的适配器设置",
	},
	option1: {
		en: "option1",
		de: "Option 1",
		ru: "Опция 1",
		pt: "Opção 1",
		nl: "Optie 1",
		fr: "Option 1",
		it: "opzione 1",
		es: "Opción 1",
		pl: "opcja 1",
		uk: "варіант1",
		"zh-cn": "选项1",
	},
	option2: {
		en: "option2",
		de: "Option 2",
		ru: "вариант 2",
		pt: "opção 2",
		nl: "Optie 2",
		fr: "Option 2",
		it: "opzione 2",
		es: "opcion 2",
		pl: "Opcja 2",
		uk: "варіант2",
		"zh-cn": "选项2",
	},
	myColor: {
		en: "myColor",
		de: "meineColor",
		ru: "Мой цвет",
		pt: "minhaCor",
		nl: "mijnKleur",
		fr: "maCouleur",
		it: "mioColore",
		es: "miColor",
		pl: "mójKolor",
		uk: "мійКолір",
		"zh-cn": "我的颜色",
	},
	myColor_tooltip: {
		en: "Description of\nmyColor",
		de: "Beschreibung von\nmyColor",
		ru: "Описание\nmyColor",
		pt: "Descrição de\nmyColor",
		nl: "Beschrijving van\nmyColor",
		fr: "Description de\nmyColor",
		it: "Descrizione di\nmyColor",
		es: "Descripción de\nmyColor",
		pl: "Opis\nmyColor",
		uk: "Опис\nmyColor",
		"zh-cn": "\nmyColor的描述",
	},
	htmlText: {
		en: "htmlText",
		de: "htmlText",
		ru: "htmlText",
		pt: "htmlText",
		nl: "htmlText",
		fr: "htmlText",
		it: "htmlText",
		es: "htmlText",
		pl: "htmlText",
		uk: "htmlText",
		"zh-cn": "htmlText",
	},
	group_extraMyset: {
		en: "extraMyset",
		de: "extraMyset",
		ru: "extraMyset",
		pt: "extraMyset",
		nl: "extraMyset",
		fr: "extraMyset",
		it: "extraMyset",
		es: "extraMyset",
		pl: "extraMyset",
		uk: "extraMyset",
		"zh-cn": "extraMyset",
	},
	extraAttr: {
		en: "extraAttr",
		de: "extraAttr",
		ru: "extraAttr",
		pt: "extraAttr",
		nl: "extraAttr",
		fr: "extraAttr",
		it: "extraAttr",
		es: "extraAttr",
		pl: "extraAttr",
		uk: "extraAttr",
		"zh-cn": "extraAttr",
	},
	Instance: {
		en: "Instance",
		de: "Instanz",
		ru: "Инстанция",
		pt: "Instância",
		nl: "Instantie",
		fr: "Instance",
		it: "Esempio",
		es: "Instancia",
		pl: "Instancja",
		uk: "Інстанція",
		"zh-cn": "例",
	},
};
